#!/bin/sh
current_dir=`pwd`
# gcc compilation
# ./configure --prefix=$current_dir --exec-prefix=$current_dir
# gcc compilation without additional underscore (does not work, does not understand -fno-second-underscore. I never figured out how to turn the 2nd underscore off, so I edited the calls in the bsplines.f90 to put in the extra underscore)
# ./configure "CC=gcc -std=c99 -fno-second-underscore" "CXX=cpp -fno-second-underscore" FC=ifort F77=ifort --prefix=$current_dir --exec-prefix=$current_dir

# --enable-sse" works on the dft cluster, but does not seem to change execution speed appreciably.
# Intel icc compilation (-std=c99 tells it to conform to the c99 standard) The "-assume no2underscore" is not necessary since it is the default for icc but not for gcc
# ./configure "CC=icc -std=c99 -assume no2underscore" "CXX=icpc -std=c99 -assume no2underscore" FC=ifort F77=ifort --prefix=$current_dir --enable-sse
#./configure "CC=icc -std=c99" "CXX=icpc -std=c99" FC=ifort F77=ifort --prefix=$current_dir --enable-sse
./configure  --prefix=$current_dir
