#!/bin/sh
current_dir=`pwd`

# gcc compilation
# The fno-second-underscore and CXX=cpp do not work.  You can avoid the 2nd underscore by telling it to use ifort or gfortran, so it does not try g77.
# ./configure "CC=gcc -std=c99 -fno-second-underscore" "CXX=cpp -fno-second-underscore" FC=ifort F77=ifort --prefix=$current_dir --exec-prefix=$current_dir
./configure "CC=gcc" FC=ifort F77=ifort --prefix=$current_dir --exec-prefix=$current_dir
#./configure FC=ifort F77=ifort --prefix=$current_dir

# --enable-sse" works on the dft cluster, but does not seem to change execution speed appreciably.
# Intel icc compilation (-std=c99 tells it to conform to the c99 standard) The "-assume no2underscore" is not necessary since it is the default for icc but not for gcc
# ./configure "CC=icc -std=c99 -assume no2underscore" "CXX=icpc -std=c99 -assume no2underscore" FC=ifort F77=ifort --prefix=$current_dir --enable-sse
# ./configure "CC=icc -std=c99" "CXX=icpc -std=c99" FC=ifort F77=ifort --prefix=$current_dir --enable-sse
# ./configure  --prefix=$current_dir
