#!/bin/bash

mkdir fortran_modules
mkdir fortran_objects
mkdir fortran_objects/MED_tools
mkdir fortran_objects/tools
mkdir fortran_objects/commons
mkdir fortran_objects/vmc
mkdir fortran_objects/vmc/MPI
mkdir fortran_objects/initialization
mkdir fortran_objects/dmc
mkdir fortran_objects/dmc/dmc_elec
mkdir fortran_objects/dmc/dmc_elec/MPI
mkdir fortran_objects/dmc/dmc_elec/MPI_global_pop_big
mkdir fortran_objects/dmc/dmc_elec/MPI_global_pop
mkdir fortran_objects/fit
mkdir fortran_objects/fit/MPI

