!         commons
!          include 'commons/common_contrl.h'
!          include 'commons/common_const.h'
!          include 'commons/common_const2.h'
!          include 'commons/common_dim.h'
!          include 'commons/common_config.h'
!          include 'commons/common_orb.h'
!          include 'commons/common_coefs.h'
!          include 'commons/common_dets.h'
!          include 'commons/common_dorb.h'
!          include 'commons/common_slater.h'
!          include 'commons/common_numbas.h'
!          include 'commons/common_atom.h'
!          include 'commons/common_basis.h'
!          include 'commons/common_basis2.h'
!          include 'commons/common_contr2.h'
!          include 'commons/common_basisnorm.h'
!          include 'commons/common_gradhess.h'
!          include 'commons/common_contrl_opt2.h'
!          include 'commons/common_forcepar.h'
!          include 'commons/common_wfsec.h'
!          include 'commons/common_doefp.h'
!          include 'commons/common_vj.h'
!          include 'commons/common_pseudo.h'
!          include 'commons/common_orbe.h'
!          include 'commons/common_contrl_per.h'
!          include 'commons/common_optim.h'
!          include 'commons/common_cntrl_opt.h'
!          include 'commons/common_derivjas.h'
!          include 'commons/common_delocc.h'
!          include 'commons/common_jaspar.h'
!          include 'commons/common_jaspar3.h'
!          include 'commons/common_jaspar4.h'
!          include 'commons/common_jaspar6.h'
!          include 'commons/common_bparm.h'
!          include 'commons/common_jasparread.h'
!          include 'commons/common_pointer.h'
!          include 'commons/common_gradhessj_nonlin.h'
!          include 'commons/common_contr3.h'
!          include 'commons/common_div_v.h'
!          include 'commons/common_phifun.h'
!          include 'commons/common_distance.h'
!          include 'commons/common_periodic.h'
!          include 'commons/common_pworbital.h'
!          include 'commons/common_force_dmc.h'
!          include 'commons/common_iterat.h'
!          include 'commons/common_qua.h'
!          include 'commons/common_jacobsave.h'
!          include 'commons/common_mpiblk.h'
!          include 'commons/common_forcest.h'
          include 'commons/common_denupdn.h'
          include 'commons/common_stepv.h'
!JT          include 'commons/common_header.h'
          include 'commons/common_lbas.h'
          include 'commons/common_jaso.h'
          include 'commons/common_jasn.h'
          include 'commons/common_vd.h'
          include 'commons/common_pjase.h'
          include 'commons/common_optimo.h'
          include 'commons/common_jel_sph2.h'
          include 'commons/common_atomtyp.h'
          include 'commons/common_contr_names.h'
          include 'commons/common_contr_ylm.h'
          include 'commons/common_pars.h'
          include 'commons/common_jaspar1.h'
          include 'commons/common_jaspar2.h'
          include 'commons/common_ncusp.h'

! for dmc
          include 'commons/common_config_dmc.h'
          include 'commons/common_branch.h'
          include 'commons/common_estsum_dmc.h'
          include 'commons/common_estcum_dmc.h'
          include 'commons/common_div_v_dmc.h'
          include 'commons/common_contrldmc.h'
          include 'commons/common_estcm2.h'
          include 'commons/common_stats.h'
          include 'commons/common_age.h'
