!         modules
          use contrl_mod
          use contr2_mod
          use const_mod
          use const2_mod
          use dim_mod
          use atom_mod
          use config_mod
          use orb_mod
          use orbe_mod
          use dorb_mod
          use slatn_mod
          use cslatn_mod
          use coefs_mod
          use dets_mod
          use slater_mod
          use numbas_mod
          use optim_mod
          use basis1_mod
          use basis2_mod
          use basisnorm_mod
          use gradhess_mod

